apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api
  labels:
    app: kubernetes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-api
  template:
    metadata:
      labels:
        app: kubernetes-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kubernetes-api
        image: projectepic/kubernetes-api:1.0.7
        resources:
          limits:
           memory: 900Mi
           cpu: "80m"
          requests:
           memory: 900Mi
           cpu: "80m"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        livenessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 5
        readinessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: FIREHOSE_CONFIG_NAME
            value: keywordsconfig
          - name: KAFKA_SERVERS
            value: kafka-0.broker.default:9092,kafka-1.broker.default:9092
          - name: TWEET_STORE_VERSION
            value: "latest"

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
spec:
  ports:
  - port: 8080
    name: client
  selector:
    app: kubernetes-api

