firehoseConfigMapName: ${FIREHOSE_CONFIG_NAME:-keywordsconfig}
firehoseConfigMapNamespace: ${FIREHOSE_CONFIG_NAMESPACE:-default}
kafkaServers: ${KAFKA_SERVERS:-"kafka-0.broker.default:9092,kafka-1.broker.default:9092"}
tweetStoreVersion: ${TWEET_STORE_VERSION:-"latest"}
