production: ${PRODUCTION:-true}

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: ${DB_USERNAME:-postgres}

  # the password
  password: ${DB_PASSWORD:-password}

  # the JDBC URL
  url: ${DB_URL:-jdbc:postgresql://google/annotationsdb?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=crypto-eon-164220:us-central1:epic-event}

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute
