apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "broker"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: solsson/kafka-persistent:0.10.1@sha256:0719b4688b666490abf4b32a3cc5c5da7bb2d6276b47377b35de5429f783e9c2
        ports:
        - containerPort: 9092
        resources:
          requests:
           cpu: "50m"
           memory: 800Mi
        livenessProbe:
          exec:
            command:
              - bin/kafka-topics.sh
              - --zookeeper
              - "zookeeper:2181"
              - --list
          initialDelaySeconds: 30
          timeoutSeconds: 5
        command:
        - sh
        - -c
        - "./bin/kafka-server-start.sh config/server.properties --override broker.id=$(hostname | awk -F'-' '{print $2}') --override auto.create.topics.enable=True"
        volumeMounts:
        - name: datadir
          mountPath: /opt/kafka/data

      volumes:
      #- name: conf
      #  emptyDir: {}
      - name: datadir
        emptyDir: {}
  # volumeClaimTemplates:
  # - metadata:
  #     name: datadir
   #    annotations:
        # volume.alpha.kubernetes.io/storage-class: anything
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 200Gi
  
