jobs:
- sparkJob:
    args:
    - gs://epic-historic-tweets/2017 Hurricane Harvey/*
    mainJarFileUri: gs://epic-spark-jars/MentionsSpark-1.0.jar
  stepId: mentions
- sparkJob:
    args:
    - gs://epic-historic-tweets/2017 Hurricane Harvey/*
    mainJarFileUri: gs://epic-spark-jars/MediaSpark-1.0.jar
  stepId: media
parameters:
- name: EVENT_NAME
  fields:
  - jobs['mentions'].sparkJob.args[0]
  - jobs['media'].sparkJob.args[0]
placement:
  managedCluster:
    clusterName: epic-spark
    config:
      gceClusterConfig:
        zoneUri: us-central1-c
      masterConfig:
        machineTypeUri: n1-standard-4
      workerConfig:
        machineTypeUri: n1-standard-4
        numInstances: 2
