apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: epic-infra-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "epic-infra-ip"
spec:
  rules:
  - http:
      paths:
      - path: /events/*
        backend:
          serviceName: events-api
          servicePort: 8080
      - path: /users/*
        backend:
           serviceName: auth-api
           servicePort: 8080
          #- path: /v2/*
          #backend:
          # serviceName: web2
          #servicePort: 8080
