apiVersion: apps/v1
kind: Deployment
metadata:

  # Replace NEW with your API name
  name: NEW-api
  labels:
    app: NEW-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NEW-api
  template:
    metadata:
      labels:
        app: NEW-api
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
         - name: keyfiles
           secret:
             secretName: keyfile
      containers:
      - name: NEW-api
      
        # This is the docker image name from your Makefile
        image: projectepic/API_NAME:1.0.0
        imagePullPolicy: Always
        volumeMounts:
         - mountPath: /private
           name: keyfiles
        resources:
          limits:
           memory: 700Mi
           cpu: "80m"
          requests:
           memory: 500Mi
           cpu: "80m"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 5
        env:
         # Google credentials for authentification
         - name: GOOGLE_APPLICATION_CREDENTIALS
           value: /private/keyfile.json

         # Credentials to access database as environment variables
         - name: DB_USERNAME
           valueFrom:
              secretKeyRef:
                name: credentials
                key: username
         - name: DB_PASSWORD
           valueFrom:
              secretKeyRef:
                name: credentials
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: NEW-api
spec:
  type: NodePort
  ports:
  - port: 8080
    name: client
  selector:
    app: NEW-api
