apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: events-api
        image: projectepic/authapi:1.0.4
        imagePullPolicy: Always
        resources:
          limits:
           memory: 900Mi
           cpu: "80m"
          requests:
           memory: 900Mi
           cpu: "80m"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /private
          name: keyfiles
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /private/keyfile.json
      volumes:
      - name: keyfiles
        secret:
          secretName: keyfile
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  type: NodePort
  ports:
  - port: 8080
    name: client
  selector:
    app: auth-api
