apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  labels:
    app: events-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: keyfiles
          secret:
            secretName: keyfile
      containers:
      - name: events-api
        image: projectepic/eventsapi:1.0.25
        imagePullPolicy: Always
        resources:
          limits:
           memory: 700Mi
           cpu: "80m"
          requests:
           memory: 500Mi
           cpu: "80m"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        volumeMounts:
        - mountPath: /private
          name: keyfiles
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 5
        env:
        - name: FIREHOSE_CONFIG_NAME
          value: keywordsconfig
        - name: KAFKA_SERVERS
          value: kafka-0.broker.default:9092,kafka-1.broker.default:9092
        - name: TWEET_STORE_VERSION
          value: "latest"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /private/keyfile.json
        
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: events-api
spec:
  type: NodePort
  ports:
  - port: 8080
    name: client
  selector:
    app: events-api
