apiVersion: apps/v1
kind: Deployment
metadata:
  name: geotag-api
  labels:
    app: geotag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geotag-api
  template:
    metadata:
      labels:
        app: geotag-api
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
         - name: keyfiles
           secret:
             secretName: keyfile
      containers:
      - name: geotag-api
        image: projectepic/geotagapi:1.0.0
        imagePullPolicy: Always
        volumeMounts:
         - mountPath: /private
           name: keyfiles
        resources:
          limits:
           memory: 1000Mi
           cpu: "80m"
          requests:
           memory: 500Mi
           cpu: "80m"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 5
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /private/keyfile.json
          
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
      nodeSelector:
        cloud.google.com/gke-nodepool: production-pool
---
apiVersion: v1
kind: Service
metadata:
  name: geotag-api
spec:
  type: NodePort
  ports:
  - port: 8080
    name: client
  selector:
    app: geotag-api
