apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets-api
  labels:
    app: tweets-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweets-api
  template:
    metadata:
      labels:
        app: tweets-api
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: keyfiles
          secret:
            secretName: keyfile
      containers:
      - name: tweets-api
        image: projectepic/tweetsapi:1.0.18
        imagePullPolicy: Always
        resources:
          limits:
           memory: 900Mi
           cpu: "80m"
          requests:
           memory: 900Mi
           cpu: "80m"
        ports:
          - containerPort: 8080
          - containerPort: 8081
        volumeMounts:
        - mountPath: /private
          name: keyfiles
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          periodSeconds: 20
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 40
          timeoutSeconds: 5
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /private/keyfile.json
        - name: DB_USERNAME
          valueFrom:
             secretKeyRef:
               name: credentials
               key: username
        - name: DB_PASSWORD
          valueFrom:
             secretKeyRef:
               name: credentials
               key: password
---
apiVersion: v1
kind: Service
metadata:
  name: tweets-api
spec:
  type: NodePort
  ports:
  - port: 8080
    name: client
  selector:
    app: tweets-api
